### ISSUE TITLE
Admin UI Remediation

### ISSUE THREAD

**Issue by laurenlangley** [firefox0102/waterwatch#15]
@firefox0102 here are some items that I was not able to fix. Can you take a stab at these?

- [x] All pages: a weird double box shadow shows up below main header when smaller widths
- [x] Collection Site Data - still have TODO listed for E. Coli and Coliform values in table
- [x] Fix map height
- [x] Chart Controls - date and reports sections should open and close similarly to site filtering w/ caret icon changing
- [x] Collection Site Data page - ‘View Site on Google Maps’ link
- [x] Collection Site Data page - ‘View Data on NWW Map’ link
- [x] Mobile nav menus: Admin and Non-Admin sites should have uppercase links (blue for default, green active) and the light blue hover color seen in select/lists
- [x] BUG! Collection Site Data > Edit Log Data - should NOT be able to bulk edit site data; also when select one, ALL are being selected
- [x] Edit Log Data - add Cancel button and functionality
- [x] Map page chart tiles: info popups fix widths to be more narrow
- [x] Map page chart controls date picker: make it a dropdown
- [x] Fix chart column height
- [x] When a site point on map is selected (from list or map), make that one point green
- [x] When click a site name from list, make that one point green and circle radius 12
- [x] LAUREN TO DO Map page chart tiles: text color warlock
- [x] LAUREN TO DO Info popup content (confirm w Erik)
- [ ] DO LAST Collection Site Data page - Do you have bandwidth to display E. Coli # colored based on values? e.g. red=high (would need high vs low values from Erik)
----------------------------
- [ ] IGNORE Sign In page: errors showing up at bottom instead of inline (shows generic “there was an issue” message) Can we display validation inline to have then retry email/password?
- [ ] IGNORE FOR NOW All date pickers - default date should be today’s date. Format MM/DD/YYYY
- [ ] IGNORE FOR NOW Collection Site Data page - when click Log New Data - link should take to Log Data page but with Collection Site already populated
- [ ] IGNORE FOR NOW Collection Site Data page - First Collection Date date format in summary and column should be MM/DD/YYYY

**Comment by firefox0102** [comment]
Fix the logbook number in the metadata structure

**Comment by firefox0102** [comment]
Filter Sidebar:
- [x] Scrolling and max height
- [x] ecoliLargeCells
- [x] Fix logbook number

**Comment by firefox0102** [comment]
- [x] Fix this bit so it's not bound to the index of the metadata structure

![image](https://user-images.githubusercontent.com/6462327/31416942-881c6c30-adfa-11e7-81c0-e2a6fab9c3bb.png)

**Comment by laurenlangley** [comment]
- [ ] Fix map height
- [ ] When a site point on map is selected (from list or map), make that one point green
