### ISSUE TITLE
Eric Feedback List

### ISSUE THREAD

**Issue by firefox0102** [firefox0102/waterwatch#18]
**Data/Map Page (SEE Note Below)**
 
- [x] A. Change Default/Home view – Either whole Chattahoochee Watershed or whole watershed from Columbus -> north

- [x] B. Include map widget/button to return to Default/Home view

- [x] C. Map Layer Updates:

    - [x] 1. Chatt Watershed Layer - Update so that it is either no-fill or 98% transparent, and increase watershed boundary pixel width x 1.5-2. Do not need the button to turn this layer off
   - [x] 2. Collection Sites Layer - Do not need the button to turn this layer off. On the Popups:
Change “Watershed Unit” to “Subwatershed (HUC12)” with the HUC12 name instead of the 
number. For “Last E.coli Result” include units and date collected ie “Last E. coli Result: 
3,609 MPN/100mL (on 5/23/17)”
   - [x] 3a. Rename “HUC Layer” -> “Subwatershed layer” or “Subwatersheds (HUC12)”
   - [x] 3b. HUC Layer should show just the HUC 12s w/i the Chatt Watershed. I think right now it shows the HUC 8s. I include pop-ups when clicking on layer that shows name (not number) of the HUC. Fyi it looks like the current pop up Also the current popup is referencing the HUC10 as opposed to 12
   - [x] 4. (LC) Add the CRK Offices Layer – Maybe small stars or something or a lab-related icon. Include pop-up w/ name of lab & address. Coords. & address in email from me on 9/26. Do not need the button to turn this layer off
   - [x] 5. Add Streams & River Flowlines & (if possible) waterbodies – The basemap doesn’t seem to show a lot of these, so it would nice to have on the map. Info is also in 9/26 email. Do not need the button to turn this layer off
   - [x] 6. Counties Layer – This layer isn’t a priority, but if we have it would ideally show all counties 
(GA & AL) that overlap the watershed and display County name in pop up upon clicking.
   - [x] D. Collection Site info – For some sites “Last Ecoli Result” does not populate in either the 
popups or graphs.
   - [x] E. Graphs – List units by axis, “Last result”, and in mouseover popup. Switch date format on 
axis to “11/24/17” instead of “24. Nov”
   - [x] F. (LL) Under “Filter” - Remove option to filter by Partner. Change “HUC” to “Subwatershed (HUC12)”
   - [x] G. (LL) Under “Chart Controls” – Change “Reports” to “Download Data”

**MAP NOTE**
Here is an example of a map we use w/ a similar style as far as displaying the Chatt Watershed Boundary, subwatersheds (HUC12), flowlines, and waterbodies. Note it also has “catchments” but you can ignore those.
https://crkeeper.maps.arcgis.com/apps/webappviewer/index.html?id=506a6371ed2945caab562b29ba9af2f3
Usr: CRKeeper4
PW: 54BubblingBirds
After you log in you’ll probably need to click the hyperlink again to get to the correct map.
 
**Log Data**

- [x] A. Remove “Lab” field – The Lab is associated w/ the site so is added when a new site is created.
- [ ] B. (ASK ERIK HOW IMPORTANT: +2 HOURS) Time fields should be in 24Hr format instead of AM/PM
- [ ] C. Data fields (including “Additional Parameters” fields should not allow negative #s
- [x] E. coli & Total coliform entry numbers should be 0-49 for large & 0-48 for small. 
- [x] Result under E. coli should just say “E. coli” instead of “Total E. coli”. 
- [x] E. coli & Total coliform - Ideally each of these results would include the units “MPN/100mL”
- [x] E. Fluorometry, Turbidity, Conductivity, Rainfall need to allow decimals
- [ ] (CAN'T REPRODUCE, NEED TO VERIFY) Much of the data validation for the different fields is not built in yet. Let me know if you want me to send a list of those rules. I think the “Edit Data” form has them mostly in place.
- [x] G. Migrate all reports
- [x] Ha. Prep all adopt-a-stream and storet data for past two weeks after Eirk sends it over.
- [x] Hb. Migrate all adopt-a-stream and storet data for past two weeks after Eirk sends it over.

**Collection Sites: Add A New Site form**

- [x] Lab should be required. 
- [x] Adopt a Stream Name and Storet Name should not be required b/c not all sites have one. If that field needs to be filled out for reports to work, maybe those w/o a name are labeled “n/a”?
- [x] If possible would be helpful to give an example next to each Lat & Long so ppl enter in correct format ie: “Latitude (eg. 34.004401)*” & “Longitude (eg. -84.350555)

**Miscellaneous General**

- [x]  Header: CRK Logo link to chattahoochee.org
- [x]  Footer: Spelling fix email address, says “chattachoochee.org”

**Comment by lcaceda** [comment]
Checkboxes added for instant gratification. And, added two data notes discussed with Erik.

**Comment by firefox0102** [comment]
New notes from today:

**Collection Sites: Click Checkbox -> “Edit Collection Site” (Similar notes to “Add a Site” above)**

- [x] A. Adopt a Stream Name and Storet Name should not be required b/c not all sites have one.
- [x] B. Lab should be required
- [x] C. If possible would be helpful to give an example next to each Lat & Long so ppl enter in correct format ie: “Latitude (eg. 34.004401)*” & “Longitude (eg. -84.350555)
- [ ] D. For exporting the data, we also need the fields “STORET Location ID (i.e. “NWW24”) and “Adopt-A-Stream ID # (i.e. S-4475)”. These should not be required fields - *NOTE This is also a new comment for “Add a Site” above and for the main Collection Sites Spreadsheet
- [x] E. “HUC Name” and “HUC” should be “HUC 12 Name” and “HUC 12”
- [x] F. Need “Cancel” option
- (WON'T IMPLEMENT) How are Lab’s edited/New Lab added?

**Collection Sites: Individual Site Page (i.e. “Ansley Stream at Winn Park”)**

- [x] A. Header Edit: Instead of HUC # -> Display “Subwatershed (HUC12): {HUC 12 Name}”.
- [x]  Please also add the Lab name in the header
- [x] B. Add units to a couple columns: Rainfall (in), Total coliform & E. coli (MPN/100mL)
- [x] C. When you check one box on left it checks them all (I think you know this)
- [ ] E. Same Select Data Range comments as above:
-  (NO FOR PERFORMANCE REASONS, can be flexible but not a good idea) Would prefer default dates to be since the beginning of time so it shows all sites we’ve ever collected.
- (MAYBE LATER) If possible, would be helpful to have the option to revert back to “Show all sites” after you have played with the date.
-  (MAYBE LATER) Also would be helpful to be able to also type the date instead of scrolling through the calendars if possible.
- (MAYBE LATER) Wish list item if possible: highlight E. coli # or change font color based on value. RED if 1,000-9,999 & PURPLE if 10,000 or greater
 
**Collection Sites: Individual Site Page (i.e. “Ansley Stream at Winn Park”) -> Edit Log Data for an Entry**

- [ ] C. (ASK ERIK HOW IMPORTANT: +2 HOURS) Time fields should be in 24Hr format instead of AM/PM
- [ ] D. Data fields (including “Additional Parameters” fields) should not allow negative #s
- [x] (FIXED BY PROPER IDS) Site name displayed in dropdown is for a different site (shows “Ada Creek at Ledan Rd”)
- [ ] I. Data validation for checking difference between reported times seems a little off (Try Collect Time=11:00AM and Inc. In Time 11:30PM or Collect Time=5:00 AM and Inc. In Time 6:00 AM)
- [x] K. Right now the E. coli & Total coliform results are not calculating correctly on EDIT LOG DATA modal
- [x] J. “Cancel” button may not be working right - If I change a parameter (i.e. change “Inc In” Time) but then click “Cancel” instead of Save, the Change is actually saved and displayed
- [x] B. Remove “Lab” field – The Lab is associated w/ the site so is added when a new site is created.
- [x] E. E. coli & Total coliform entry numbers should be 0-49 for large & 0-48 for small.
- [x] Result under E. coli should just say “E. coli” instead of “Total E. coli”.
- [x] Ideally each of these results would include the units “MPN/100mL”
- [x] F. Fluorometry, Turbidity, Conductivity, Rainfall need to allow decimals
- [x] G. Right now the E. coli & Total coliform results are not calculating correctly
- (FIXED BY PROPER IDS) If you open the Edit Log Data page, edit one of the parameters (i.e. Rainfall) and save -> E.coli and Total col save as blank
- (FIXED BY PROPER IDS) If I edit an entry -> Save -> Click “Back to List of Collection Sites” -> and click on the site again then the data I updated and saved is lost and the pre-edit data is show in the chart

**Comment by firefox0102** [comment]
Peter TODO:
- [x] Expand sidebar filters and fix the scrolling past the footer
![image](https://user-images.githubusercontent.com/6462327/31695141-c028686e-b376-11e7-877b-764aee0291fc.png)
- [x] make map fixed on screen
- [x] Add max-height to filter sections (e.g. to allow for HUC list of 63 items)
- [x] Allow decimals on specified fields
