### ISSUE TITLE
The Final Countdown

### ISSUE THREAD

**Issue by laurenlangley** [firefox0102/waterwatch#19]
**TO DO**

- [ ] Transfer CRK Firebase Account
- [ ] Report Exports in Admin
- [x] Report Exports on Data Page
- [ ] Create User Guide (if needed)
- [x] Finish modal styles
- [x] Final copy for chart ‘more info’ modals
- [ ] Final copy for About page
- [ ] Fix site routing issues
- [ ] Collection site: default date picker start date should be first collection date of selection
- [x] HUCS include pop-ups when clicking on layer that shows name
- [x] LABS Include pop-up w/ name of lab & address (fixed-ish, lab name only for now)
- [x] Map layer: add Streams & River Flowlines & (if possible) waterbodies – The base map doesn’t seem to show a lot of these, so it would nice to have on the map. Info is also in 9/26 email. Do not need the button to turn this layer off
- [x] Graphs – List units by axis, “Last result”, and in mouseover popup. Switch date format on axis to “11/24/17" instead of “24. Nov”
- [x] (2+ hours LOE) Time fields should be in 24Hr format instead of AM/PM
- [x] Data fields (including “Additional Parameters” fields) should not allow negative #s
- [x] (Pete) Edit Collection Site: private/public checkbox interaction ui not working
- [x] Adjust header logos

**Question for Erik**

• Data validation for checking difference between reported times seems a little off (Try Collect Time=11:00AM and Inc. In Time 11:30PM or Collect Time=5:00 AM and Inc. In Time 6:00 AM) - **What is the validation suppose to be?**

• When editing a collection site report - Much of the data validation for the different fields is not built in yet. Let me know if you want me to send a list of those rules. I think the “Edit Data” form has them mostly in place.
***Need to discuss rules with eric***

**WILL NOT GET TO**

• Collection Site Data page - display E. Coli # colored based on values? e.g. red=high (would need high vs low values from Erik)
 • Sign In page: errors showing up at bottom instead of inline (shows generic “there was an issue” message) Can we display validation inline to have then retry email/password?
• All date pickers - default date should be today’s date. Format MM/DD/YYYY
• Collection Site Data page - when click Log New Data - link should take to Log Data page but with Collection Site already populated
• Collection Site Data page - First Collection Date date format in summary and column should be MM/DD/YYYY

**Comment by lslangley** [comment]
Adjust map height on mobile so it scales with the screen
