### ISSUE TITLE
All Outstanding To Address

### ISSUE THREAD

**Issue by laurenlangley** [firefox0102/waterwatch#22]
# In Scope: Complete by 11/5

### Data/Map Page
- [x] Layers: Instead of allowing users to turn off/on layers, Would prefer to remove those buttons and leave layers on.
- [x] Layers: Flowlines and waterbodies - load only at certain zoom; include in base map versus load in (take out toggle layer button). Erik can help prep layers because of hours
- [x] Layers: Leslie send Flowlines url to Mike for interpretation
- [x] Layers: HUC only display at certain zoom if possible. Take out toggle layer button
- [x] (Note: This happens in real time, it's pretty sick) Confirm we’re not showing inactive site data and points on map
- [x] Summary and charts: For “Last E.coli Result” include date collected ie “Last E. coli Result: 3,609 MPN/100mL (on 5/23/17)”
- [x] Charts: date format, change MM/DD/YYYY to MM/DD/YY
- [x] Add “First Collected: {earliest sample date}” on the display somewhere so people know how far back they can look for data
- [x] Filter: Lab names instead of abbrev. HW-CV = Clarksville, HW = Gainesville, AT = Atlanta, MC = Lagrange
- [x] Filter list: populate the list with the Subwatershed (HUC12) Name field as opposed to the numbers
- [x] Have a y-axis max of 8K level for E. Coli for scale (confirm)
- [x] To make clicking on sites on map easier: change cursor hand to pointer finger or arrow
- [x] When selecting site, prefer not to zoom in as much, bring back “2 clicks”
- [x] Style HUC and Lab popups
- [x] Mobile: Difficult to scroll down to view Graphs
- [x] Mobile: Some map buttons appear cut off and some popups ie select date calendar is cut off
- [x] Mobile: Adjust map height on mobile so it scales with the screen
- [x] Header logos: CRK same height with NWW

### Log Data and Edit Data
- [x] Time fields should be in 24Hr format instead of AM/PM
- [x] Data fields (including “Additional Parameters” fields should not allow negative #s (still allowing for coliform and E. coli)
- [x] E. coli & Total Coliform entry numbers should be 0-49 for large & 0-48 for small
- [x] E. coli & Total Coliform - round to nearest tenth decimal
- [x] If “Incubation Out” Time is not between 18-22 hours since “Incubation In”, do not allow to log data
- [x] Site Selection - Change Dropdown list for site selection to the Site abbreviation list instead of full name
- [x] When you submit but data is incomplete, box that says “Please enter valid value” pops up and disappears. Is it possible to prevent this from disappearing again until the data is fixed?
- [x] Move 'Notes' section out of Additional Parameters to be placed beneath Analyst field
- [ ] Logbook number - start with where left off when kicked over live - Pete/Leslie to make put that number in db when launch
- [x] logging data for a collectionSite throws the following error - "Error: Reference.set failed: First argument contains undefined in property 'collectionSites.BJohnOrchard.lastEColiResult' LogData.vue?121c:633"

### Collection Sites: Add New Collection Site and Edit Collection Site
- [x] For exporting the data, we also need the fields "STORET Name", “STORET Location ID (i.e. “NWW24”) and “Adopt-A-Stream ID # (i.e. S-4475)”. These should not be required fields
- [x] Add false value to imported sites for private/public
- [x] Collection Site one-off - have a catch-all ‘Site for that’. What fields and validations are then req vs not req?
- [ ] New collection site added - link up to Firebase geojson file

### Collection Sites List
- [x] Get rid of bulk editing but not bulk export/archive
- [x] Include search parameter to include search by Abbv
- [x] Ability to archive and unarchive
- [x] Do we still need private/public? Archive = gray. Priv = hidden. What about one-off sites?
- [ ] For exporting the data, we also need the fields “STORET Location ID (i.e. “NWW24”) and “Adopt-A-Stream ID # (i.e. S-4475)”; STORET Activity start date = collection date. Column L = NWWXXX + Date

###Adding New Site
-[ ] Unable to create new site. Error: Reference.set failed: First argument contains NaN in property 'metaData.totalSites' 

### Export Reports
- [ ] Report Exports in Admin - Storet Concatenation of storetID + collectionDate in YYYYMMDD format, and activity date as YYYY-MM-DD
- [x] Report Exports on Data Page

### Other Tasks 
- [x] Erik to send Add/Edit a Site required fields
- [ ] Erik to test validation rules
- [x] Fix site routing issues
- [ ] Make sure Collection Sites URL redirects to data/map page if signed out
- [ ] Add new collection site data and one off data before final deploy
- [ ] Leslie to add Google Analytics tracking code
- [ ] Firebase: help Erik set up Automated Backups to Google Cloud Storage bucket
- [ ] Firebase: transfer account name to CRK and payment information
- [x] Firebase: provide CRK with cost estimate for database, storage, and hosting
- [ ] Redirect/mask name/url to https://chattahoochee.org/nww/
- [ ] Train CRK on Firebase

# Out of Scope: Evaluate for contract after 11/5
• Wish list item if possible: highlight E. coli # or change font color based on value. RED if 1,000-9,999 & PURPLE if 10,000 or greater
• Still allow access to map view when Logged In as admin
• Archived site: Implement gray dot color on map for archived sites
• Chart control date picker: Limit the available years you can choose to 2009-2030 (if possible)
• Filter list: Add a way to easily remove/clear/reset the filter
• Select Data Range: If possible, would be helpful to have the option to revert back to “Show all sites” after you have played with the data.
• Add new site from field: drop pin, also mouse coordinates on map to get lat/long
• If possible – Hide or highlight sites on map based on filter
• If possible – Auto alter color of points on map based on Active/Inactive Status -> Inactive sites (haven’t been sampled in last 6 mo) become a light grey dot
• Collection Sites: Individual Site - Data range: If possible, would be helpful to have the option to revert back to “Show all sites” after you have played with the data.
• Add/Edit Site: HUC 12 Number*- Ideally this would either autofill via link to HUC name selected above and so would not need to be a field to complete, or it would be combined into a single dropdown “HUC Name (HUC Number)*”
• Select Date: Also would be helpful to be able to also type the date instead of scrolling through the calendars if possible.
• Data/Map Page - Is it possible to allow the public to export a spreadsheet of the sites w/ coordinates for their own mapping purposes (same as #5 below)?
• CollectionSites Page - Is it possible to Export this Collection Site Chart as displayed on the page, including the Coordinates, etc.? 
• In the long term, Mike has expressed interest in a different arrangement for this, where the Log Data page would have a box near the Station Name field that you could check (“1-Time Sample Site”) that would allow you to write the identifier for the site into a text box. And the “Notes” field would go back under “Additional parameters.” I realize that this is almost the same as what you have done and would involve a significant amount of additional work, but can you give us a quote on what it would take to set it up that way?

**Comment by lslangley** [comment]
transefered
