### ISSUE TITLE
final countdown

### ISSUE THREAD

**Issue by lslangley** [firefox0102/waterwatch#24]
# Exports
### xls

- [x] SiteName should pull from logbookAbbr. Is it possible to pull from collectionSites in DB or does it need to be added as a field in reports? - **_Pete/Lesle_**
- [ ] Fluorometry - returns "undefined"- update in DB where this field is mostly empty - **_Leslie_**

### Adopt-a-Stream
- [x] Site S- must pull from stationName + (aasnumber). aasNumber lives in collectionSites DB - **_Pete_**
- [x] Change headers to the following titles and order: 
Site S-, Event date (mm/dd/yyyy), Time sample collected (hh:mm), Total # of particip, Time spent sampling (minutes), Adopt-A-Stream monitors, Amount of rain (inches), In last (hours), Conductivity (µS/cm), Turbidity (NTU), Other than Petri film?, E.coli IDEXX (MPN / 100mL) - **_Pete_**
### Storet
- [x] Change headers to match the following titles and order: 
Project ID, Monitoring Location ID, L , Activity Type, Activity Media Name, Activity Start Time, Activity Start Time Zone, Activity Depth/Height Measure, Activity Depth/Height Unit, Sample Collection Method ID, Sample Collection Equipment Name, Sample Collection Equipment Comment, Data Logger Line, Characteristic Name, Method Speciation, Result Detection Condition, Result Value, Result Unit, Result Measure Qualifier, Result Sample Fraction, Result Status, Statistical Base Code, Result Value Type, Result Analytical Method ID, Result Analytical Method Context, Analysis Start Date, Result Detection/Quantitation Limit Type, Result Detection/Quantitation Limit Measure, Result Detection/Quantitation Limit Unit, Result Comment **_Pete_**
- [x] Monitoring Location ID - pulls from storetId (to be added by Leslie), **_Pete_**
- [x] L pulls from storetName + collectionDate in YYYYMMDD format **_Pete_**
- [x] Activity Start Data needs to be in YYYY-MM-DD format **_Pete_**

For all of the above reference this doc: [Generated_Reports](https://docs.google.com/spreadsheets/d/1D18Ydb4ssxV7uH1RMMRMx1HiQ6GKD4bVlRUUIsVci0Y/edit?usp=sharing )

### Adopt-a-Stream 
- [x] Site S- must pull from stationName + (aasnumber). aasNumber lives in collectionSites DB - **_Pete/Leslie_**
### Storet
- [x] Monitoring Location ID - pulls from stationName **_Leslie_**
- [x] L pulls from storetName + collectionDate in YYYYMMDD format **_Pete/Leslie_**
- [x] Activity Start Data needs to be in YYYY-MM-DD format **_Pete/Leslie_**

# DB updates
- [x] add storedId to reports **_Leslie_**
- [ ] add logbookAbbr to reports? Nope. change pull of reports to pull from collectionSite db
- [x] add aasNumber to reports?

# GeoJson on the fly updates
- [ ] research and tinker **_Pete/Leslie_**

# Google Analytics 
- [ ] add it **_Leslie_**

# URL transfer/masking
- [ ] research and tinker

# transfer Firebase account 
- [ ] do it at the end and pair with a training session **_Leslie_**

**Comment by firefox0102** [comment]
Questions/Comments:
- Should we add a check in for each value to see if it's undefined, and then just leave it as an empty string instead?
- I found an obnoxious bug, the download excel links on the collection sites exporting modal don't seem to work 100% of the time. It looks like only 2 out of 3 will ever work, and it's random. I shall investigate!

**Comment by lslangley** [comment]
On obnoxious bug - out looks like it times out

**Comment by lslangley** [comment]
Yes to relaying an empty string for undefined values.
