### ISSUE TITLE
From 12/01 Meeting

### ISSUE THREAD

**Issue by lslangley** [firefox0102/waterwatch#25]
# Critical 

## Edit Logged Data
- [x] Edit logged data - saving error with times "Uncaught TypeError: Cannot read property 'collectionTime' of undefined
    at formRules.incubationTimeRules " 
- [x]  highlight saving error(s)?
- [x] Conductivity value not persisting when saved

##  Data inputs everywhere
- [x] Fluorometry to the 3'd decimal (x.xxx)

## Collection Data range selection on Collection Sites page and Collection Site (reports) page
- [ ] Currently, the data range calls on the lastCollectionDate.  It needs to reference collectionDate in the reports and scan for matches. So that if they want to know what sites were collected during a week in September (say sept 3 - 10) it would pull sites that were collected then even if the lastCollectionDate entry is in November or some later date.  **( Potential Fix Add Reports Data Page)**

## STORET Exports
- [ ] not always exporting when generated and clicked..why? **( Potential Fix Add Reports Data Page)**

- [x] "Activity Start Date" field valued must return "YYYY-MM-DD" date format **Works on Pete's comp but not Leslie's.**
- [x] "Activity Start Time" field valued must return  "HH:mm:ss" time format

## Map 
- [x] map flickering

## DB
- [ ] populate allReports with...all reports
- [ ] fix STORET Location Fields Inputs  - update 
- [ ] empty "monitoring location ID" update to return undefined
- [ ] add data from September when Erik sends it
- [x] reconnect OneOffs

## URL switch 
- [ ] they want chattahoochee.org/nww to become this site 

# Nice to fix/add

# Flickering 
- [x] let's troubleshoot why flickering occurs on Map and Tables when more than 25 rows shown

## New Export 
- [ ] add ability to export all the fields shown in the tables - at very least add lat and log columns 

## Generate geojson when new site added
- [ ] fix generate map point button with jobs function to update link in code or maintain the same url
- [ ] if an existing site is made private - it is removed from the filter table but map point still exists

**Comment by firefox0102** [comment]
@lcaceda I can't reproduce this one
'Conductivity value not persisting when saved'
any specific one I can test with?
Yup. Here's the url and pictures for an example of attempting add a conductivity value after by editing an existing site record. 
https://waterwatch-cb707.firebaseapp.com/collectionSiteData/OneOffs
<img width="1276" alt="screen shot 2017-12-03 at 10 35 08 am" src="https://user-images.githubusercontent.com/3924239/33526926-17119254-d816-11e7-8f29-deabf2c9f728.png">
<img width="1269" alt="screen shot 2017-12-03 at 10 35 21 am" src="https://user-images.githubusercontent.com/3924239/33526927-18c501d0-d816-11e7-8997-49135425f7c8.png">

**Comment by firefox0102** [comment]
@lcaceda does this mean that they want to force 3 decimals at all times, or limit it in the form validation
'Fluorometry to the 3'd decimal (x.xxx)'

@firefox0102 Good question :) i think the latter. I'll double check with Erik. I know they want to at least allow for it. tbd

**Comment by firefox0102** [comment]
@lcaceda don't really get this one either, it seems to be working fine

"Activity Start Date" field valued must return "YYYY-MM-DD" date format

![image](https://user-images.githubusercontent.com/6462327/33525959-2023008a-d807-11e7-95c9-b04aeca5f3d3.png)

@firefox0102  yikes. I'm glad to see it's working for you, ha. It's still not working for me. 
Are you running locally from master, lc/map, or testing from the deployed app (https://waterwatch-cb707.firebaseapp.com)?
<img width="818" alt="screen shot 2017-12-03 at 10 49 34 am" src="https://user-images.githubusercontent.com/3924239/33527040-b148681a-d817-11e7-9709-410d79396e9a.png">
<img width="1233" alt="screen shot 2017-12-03 at 10 44 38 am" src="https://user-images.githubusercontent.com/3924239/33527002-3430a3ce-d817-11e7-9cc3-53bca5b50d64.png">
