### ISSUE TITLE
Buglist

### ISSUE THREAD

**Issue by firefox0102** [firefox0102/waterwatch#26]
- [x] Date format issue
- [x] Storet ID mismatch keyname
- [x] Adopt a stream mismatch keyname
- [x] Log data dropdown list needs to be alphabetized
- [x] Verify that date fix also fixes problem with missing log data after first log
- [x]  On the Log Data form, could you update the Rainfall (in) to Rainfall (in) [trace = 0.001]
- [x] Would it be difficult to also make the “Incubation Out Time” field allow you to type in the time?
- [x] Don't use google maps url prop, use the long and lat if they're populated
- [x]  It is currently possible to Log Data without entering any data including the Site Name. It seems like having a date and a site name should always be required.
- [x] Many of the HUC 12s within the Chattahoochee Watershed are missing from the dropdown in the Add a site and edit a site forms – Some that I noticed that are missing are: Middle Flat Shoal Creek and Flatrock Creek-Bull Creek, Lower Mulberry Creek. These show up on the map, but not in dropdown
- [x] The “Last Ecoli result” does not seem to be populating in the Collection Sites Spreadsheet and on the Map for some – i.e. see Utoy Creek North at Harlan Rd
- [x] Edit site report - changing collection site doesn't seem to work?
- [x] Add ability to filter by lab on the reports page
- [x] On Adopt a stream report, Mike’s name is misspelled in column F “Micheal Meyer (25064)” should be “Michael Meyer (25064)”
- [x] - On Export to XLS report– The first Column’s header should be “Logbook #” or “#”, not “site ID #”
- [x] This one is a pretty big issue: If someone changes the name of a sample site (or its Adopt a Stream or Storet Name) and later wants to run a report of all of the samples that have been collected at that site, it is not possible to do, because the old reports have stored the data under the site’s previous name. The report would only show all of the data collected since the name change. This actually presents a big problem and would impair the utility of the database as a long term data storage tool. I’m not sure how you would solve that issue with the new reports configuration.

**Comment by firefox0102** [comment]
Reporting issues -
- On Export to XLS report– The first Column’s header should be “Logbook #” or “#”, not “site ID #”
- On Adopt a stream report, Mike’s name is misspelled in column F “Micheal Meyer (25064)” should be “Michael Meyer (25064)”
- Each lab needs to be able to just export the data for their lab each week. This was possible to do using the old configuration when you had the option to generate reports on the Collection Sites page by typing the name of the lab in the search bar.
- This one is a pretty big issue: If someone changes the name of a sample site (or its Adopt a Stream or Storet Name) and later wants to run a report of all of the samples that have been collected at that site, it is not possible to do, because the old reports have stored the data under the site’s previous name. The report would only show all of the data collected since the name change. This actually presents a big problem and would impair the utility of the database as a long term data storage tool. I’m not sure how you would solve that issue with the new reports configuration.
 
The easiest way (and probably our preferred way at this point) to fix these last 2 reports issues and a couple others I didn’t mention would be to restore the ability to export reports from the Collection Sites Page but also have the new configuration in place so that someone interested in looking at a single site over time or all of the sites from one lab could use the old configuration and someone interested in a specific date range could use the new one.

**Comment by firefox0102** [comment]
6 - Greater Than Less Than (Inequalities) – When calculating E.coli and Total Coliform, sometimes the result should have a < or > symbol in front of it for it to be scientifically correct (i.e. <50 or >241,960). Right now, the app seems to make anything that would have had a “<” symbol equal to zero b/c the “<1” coefficient for that calculation was changed to 0. Anything that would have had a “>” symbol is seems to be just assigned a higher number b/c the coefficient for that calculation was changed from “>2419.6” to “>2420”. Retaining those symbols is actually pretty important, though it would be ok if the symbol was left off and number was used for the graph calculations (i.e. in that case <50 would be treated as 50). My proposal for solving this in the database would be to have a new field in the DB for the symbol for each the coliform values. In Firebase they could be called “EcoliInequal” and “TcoliInequal”. Unless there were an inequality, these fields would remain blank (or contain a [space] or “=” sign if a character is needed). In the event of an inequality, the “>” or “<” would be populated in this field. Then anywhere that the respective coliform values appear in the App (ie “Last E.coli result” in map popup and graph header, on the export to XLS report and in the export to STORET report), the code would reference {EcoliInequal}{totalEcoli}. I get the impression that it would be a heavy lift to scrub and reupload the data currently in the database, so its fine if we leave them as they currently are in the system.

**Comment by firefox0102** [comment]
note to @lslangley 
We're going to want to go ahead and pull the json file and do a find and replace from 'adoptAStreamId ---> aasNumber' as well as 'storetLocationId --> storetId'
I can totally do this, just letting you know

@firefox0102 done

**Comment by lslangley** [comment]
"Firebase naming – the way new sites and samples are named (i.e. “-L-rRCP7ECmoyZYOmc1z”) makes it very difficult to go in to firebase and delete a site or an entry that was created by mistake. Curious if there is an easy way to improve this? Whether it was allowing you to delete a site in the App interface with a tiny secret button or something? One idea I had for this would be if we have a private site called “Delete” then if someone accidentally logged an incorrect data point they could pull up that data point in from the Collections Sites spreadsheet -> Click edit > and change the Collection site name for that sample to “Delete”. It seems like this would be the easiest way to deal with allowing people to delete a data point. But currently, if you do this and change the collection site name for a data point in the edit form it does not actually change. "

@firefox0102 - It might easier to add a delete function to the reports page bc the allReports files is HUGE and rough to manage unless you can work in the command line which I don't think Erik can.

**Comment by firefox0102** [comment]
It's pretty easy to add a delete button, I can add it to the collection sites data page or all reports

**Comment by lslangley** [comment]
Ok cool. Just the reports page. Erik can delete collection sites from the firebase DB portal.

**Comment by lslangley** [comment]
@firefox0102 - 
Do you mind checking if it takes you ~10 seconds to load the [allReports](https://waterwatch-cb707.firebaseapp.com/allreports) page? Hoping it's just my internet.

**So all that is left is:** 
- [x] On Export to XLS report– The first Column’s header should be “Logbook #” or “#”, not “site ID #”
- [ ] adding a delete option with an "are you sure?" alert dialogue modal
- [ ] re-deploy

**Comment by lslangley** [comment]
@firefox0102 
Were you able to solve for this?

> 6 - Greater Than Less Than (Inequalities) – When calculating E.coli and Total Coliform, sometimes the result should have a < or > symbol in front of it for it to be scientifically correct (i.e. <50 or >241,960). Right now, the app seems to make anything that would have had a “<” symbol equal to zero b/c the “<1” coefficient for that calculation was changed to 0. Anything that would have had a “>” symbol is seems to be just assigned a higher number b/c the coefficient for that calculation was changed from “>2419.6” to “>2420”. Retaining those symbols is actually pretty important, though it would be ok if the symbol was left off and number was used for the graph calculations (i.e. in that case <50 would be treated as 50). My proposal for solving this in the database would be to have a new field in the DB for the symbol for each the coliform values. In Firebase they could be called “EcoliInequal” and “TcoliInequal”. Unless there were an inequality, these fields would remain blank (or contain a [space] or “=” sign if a character is needed). In the event of an inequality, the “>” or “<” would be populated in this field. Then anywhere that the respective coliform values appear in the App (ie “Last E.coli result” in map popup and graph header, on the export to XLS report and in the export to STORET report), the code would reference {EcoliInequal}{totalEcoli}. I get the impression that it would be a heavy lift to scrub and reupload the data currently in the database, so its fine if we leave them as they currently are in the system.

**Comment by firefox0102** [comment]
@lslangley It takes a long time to load all reports for me, the server we're on probably isn't that powerful. We can either pick a smaller date range, or look into other filtering..

**Comment by lslangley** [comment]
@firefox0102  Ok. It's loading a bit faster today. I think I'll go in and set it to 2 months back to speed it up a hair.
