### ISSUE TITLE
collection sites export by date range error

### ISSUE THREAD

**Issue by lslangley** [firefox0102/waterwatch#34]
@firefox0102 
From the [Collection sites page](https://waterwatch-cb707.firebaseapp.com/collectionSites), they need to be able to export reports from many sites for a discreet time range.

So if you type in "Atlanta", select all the sites that populate, select the past two weeks you, and then export any report you'll notice that the export is incorrect.

The reports page is also not exporting correctly. If a date range is selected (the last month for example), select all and then export. It exports all report entries not just the date range filtered for.

I'll be working on updating data with the latest info and typing up a user guide for Erik.

**Comment by firefox0102** [comment]
@lslangley do we still need exporting on the reports page?
Or are they really only going to use the Collection Sites page to export?

**Comment by lslangley** [comment]
They're mostly going to use the collection sites page for exports. The reports page was removed/deleted. So we have the collection sites page and the individual site reports page. The functionality of the previous reports page was going to be moved up to the collection sites page.

**Comment by firefox0102** [comment]
Sorry, I meant the individual reports page
Do they still need to be able to export from that?

**Comment by lslangley** [comment]
Ah. Yes.

**Comment by firefox0102** [comment]
@lslangley ok fixed that, exporting works with the date filter (not selection though, hiding it when they select anything solves that)
I tried to export data and I did see another bug, so I fixed that in the firebase function
I exported data for 2017-11-13 to 2017-11-20 and everything seems fine to me now?
